### ISSUE TITLE
Can't enable verbose logging

### ISSUE THREAD

**Issue by zachlayman-applitools** [applitools/eyes-webdriverio5-service#16]
https://github.com/applitools/eyes-webdriverio5-service/blob/62ebe4b975b37339e1779afbd5398fc6ca47e30a/src/EyesService.js#L34

When setting enebleEyesLogs to true, I get the following error:

[0-0] 2020-01-30T15:24:10.369Z ERROR @wdio/local-runner:utils: Error in beforeSession: ReferenceError: ConsoleLogHandler is not defined

Is there simply an import missing?

Thanks

**Comment by tourdedave** [comment]
Fixed in https://github.com/applitools/eyes.sdk.javascript1/commit/a647a1372b5a09d48179074ce5b0eae4baed512c#diff-a62039a9914653a76379ffe5fb8127d1

Note that the repo has moved to https://github.com/applitools/eyes.sdk.javascript1
